import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";
import fs from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const renameStyles = {
	name: "rename-styles",
	setup(build) {
		build.onEnd(() => {
			const { outfile } = build.initialOptions;
			const outcss = outfile.replace(/\.js$/, ".css");
			const target = outfile.replace(/main\.js$/, "styles.css");
			if (fs.existsSync(outcss)) {
				if (fs.existsSync(target)) fs.unlinkSync(target);
				fs.renameSync(outcss, target);
				console.log("Generated styles.css");
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [renameStyles],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	platform: "node",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: false,
	define: prod ? { "process.env.NODE_ENV": '"production"' } : {},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
